name = "JialiangCraft"
author = "gujialiang123"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e66774cc917ca6d8be24bd5c916e8906425fb21f333bcadd87b0cbdb722d9ca"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
